### ISSUE TITLE
Background datafile loading failing to close file resource

### ISSUE THREAD

**Issue by sschendel** [optimizely/android-sdk#111]
Version:
`    compile 'com.optimizely.ab:android-sdk:1.3.0'`

Captured strict mode exception:
```
04-28 09:33:09.039: E/Surface(21300): getSlotFromBufferLocked: unknown buffer: 0xa9f76820
04-28 09:33:09.088: E/StrictMode(21300): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
04-28 09:33:09.088: E/StrictMode(21300): java.lang.Throwable: Explicit termination method 'close' not called
04-28 09:33:09.088: E/StrictMode(21300): 	at dalvik.system.CloseGuard.open(CloseGuard.java:180)
04-28 09:33:09.088: E/StrictMode(21300): 	at java.io.FileInputStream.<init>(FileInputStream.java:78)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.app.ContextImpl.openFileInput(ContextImpl.java:384)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:177)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.optimizely.ab.android.shared.Cache.load(Cache.java:61)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.optimizely.ab.android.sdk.DataFileCache.load(DataFileCache.java:47)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.optimizely.ab.android.sdk.DataFileLoader$LoadDataFileFromCacheTask.doInBackground(DataFileLoader.java:101)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.optimizely.ab.android.sdk.DataFileLoader$LoadDataFileFromCacheTask.doInBackground(DataFileLoader.java:85)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
04-28 09:33:09.088: E/StrictMode(21300): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-28 09:33:09.088: E/StrictMode(21300): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-28 09:33:09.088: E/StrictMode(21300): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-28 09:33:09.088: E/StrictMode(21300): 	at java.lang.Thread.run(Thread.java:818)
04-28 09:33:09.088: E/StrictMode(21300): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
04-28 09:33:09.088: E/StrictMode(21300): java.lang.Throwable: Explicit termination method 'close' not called
04-28 09:33:09.088: E/StrictMode(21300): 	at dalvik.system.CloseGuard.open(CloseGuard.java:180)
04-28 09:33:09.088: E/StrictMode(21300): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:89)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.app.ContextImpl.openFileOutput(ContextImpl.java:393)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.content.ContextWrapper.openFileOutput(ContextWrapper.java:183)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.optimizely.ab.android.shared.Cache.save(Cache.java:108)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.optimizely.ab.android.sdk.BackgroundWatchersCache.save(BackgroundWatchersCache.java:122)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.optimizely.ab.android.sdk.BackgroundWatchersCache.setIsWatching(BackgroundWatchersCache.java:56)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.optimizely.ab.android.sdk.DataFileService.onStartCommand(DataFileService.java:77)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.app.ActivityThread.-wrap17(ActivityThread.java)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.os.Looper.loop(Looper.java:148)
04-28 09:33:09.088: E/StrictMode(21300): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
04-28 09:33:09.088: E/StrictMode(21300): 	at java.lang.reflect.Method.invoke(Native Method)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-28 09:33:09.088: E/StrictMode(21300): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-28 09:33:09.140: E/Surface(21300): getSlotFromBufferLocked: unknown buffer: 0xae432570
```

**Comment by elliotykim** [comment]
Hi @sschendel,

We've recently addressed this issue:
https://github.com/optimizely/android-sdk/blob/master/event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventDAO.java#L128-L135

It was released with 1.4.0-alpha: https://github.com/optimizely/android-sdk/releases/tag/1.4.0-alpha.
