### ISSUE TITLE
NoClassDefFoundError on API 17 (Basically a duplicate of issue 124)

### ISSUE THREAD

**Issue by javierarboleda** [optimizely/android-sdk#147]
I'm running into the same NoClassDefFoundError experienced in issue #124 . The app isn't crashing, but my variations are coming back as null, and I'm never able to assign the optimizelyClient member variable to the OptimizelyClient object passed in OptimizelStartListener.onStart.

I'm able to consistently reproduce on our devices running API 17.

`
09-06 16:08:52.557 3661-3661/com.clover.apps E/Optly.androidSdk: Unable to build OptimizelyClient instance
                                                                 java.lang.NoClassDefFoundError: javax/annotation/Nonnull
                                                                     at java.lang.reflect.Method.getParameterAnnotations(Native Method)
                                                                     at java.lang.reflect.Constructor.getParameterAnnotations(Constructor.java:229)
                                                                     at com.fasterxml.jackson.databind.introspect.AnnotatedClass._constructConstructor(AnnotatedClass.java:754)
                                                                     at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveCreators(AnnotatedClass.java:335)
                                                                     at com.fasterxml.jackson.databind.introspect.AnnotatedClass.getConstructors(AnnotatedClass.java:227)
                                                                     at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:414)
                                                                     at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collect(POJOPropertiesCollector.java:234)
                                                                     at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:142)
                                                                     at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(BasicClassIntrospector.java:81)
                                                                     at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(BasicClassIntrospector.java:11)
                                                                     at com.fasterxml.jackson.databind.DeserializationConfig.introspect(DeserializationConfig.java:507)
                                                                     at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:329)
                                                                     at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:267)
                                                                     at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:247)
                                                                     at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:146)
                                                                     at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:305)
                                                                     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:151)
                                                                     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:23)
                                                                     at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:328)
                                                                     at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:2990)
                                                                     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2884)
                                                                     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2041)
                                                                     at com.optimizely.ab.config.parser.ProjectConfigJacksonDeserializer.deserialize(ProjectConfigJacksonDeserializer.java:56)
                                                                     at com.optimizely.ab.config.parser.ProjectConfigJacksonDeserializer.deserialize(ProjectConfigJacksonDeserializer.java:38)
                                                                     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
                                                                     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
                                                                     at com.optimizely.ab.config.parser.JacksonConfigParser.parseProjectConfig(JacksonConfigParser.java:39)
                                                                     at com.optimizely.ab.Optimizely.getProjectConfig(Optimizely.java:496)
                                                                     at com.optimizely.ab.Optimizely.access$000(Optimizely.java:83)
                                                                     at com.optimizely.ab.Optimizely$Builder.build(Optimizely.java:760)
                                                                     at com.optimizely.ab.android.sdk.OptimizelyManager.buildOptimizely(OptimizelyManager.java:390)
                                                                     at com.optimizely.ab.android.sdk.OptimizelyManager.injectOptimizely(OptimizelyManager.java:339)
                                                                     at com.optimizely.ab.android.sdk.OptimizelyManager$1.onDatafileLoaded(OptimizelyManager.java:230)
                                                                     at com.optimizely.ab.android.datafile_handler.DefaultDatafileHandler$1.onDatafileLoaded(DefaultDatafileHandler.java:80)
                                                                     at com.optimizely.ab.android.datafile_handler.DatafileLoader.notify(DatafileLoader.java:86)
                                                                     at com.optimizely.ab.android.datafile_handler.DatafileLoader.access$000(DatafileLoader.java:34)
                                                                     at com.optimizely.ab.android.datafile_handler.DatafileLoader$RequestDatafileFromClientTask.onPostExecute(DatafileLoader.java:167)
                                                                     at com.optimizely.ab.android.datafile_handler.DatafileLoader$RequestDatafileFromClientTask.onPostExecute(DatafileLoader.java:118)
                                                                 	at android.os.AsyncTask.finish(AsyncTas
`

**Comment by thomaszurkan-optimizely** [comment]
Can you try adding this to your gradle file dependancies and see if the issue still comes up in API 17?
compile group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version:'1.7.1'

**Comment by javierarboleda** [comment]
From comment I left on #126 :

If you're now catching any error or exception, onStart is not called when there's an error or exception thrown. This would be an issue if anyone is doing any significant logic or navigation calls, such as what you provide in your developers example code where you have an activity starting from the onStart method:


    optimizelyManager.initialize(this, new OptimizelyStartListener()  {
      @Override public void onStart(OptimizelyClient optimizely) {
          assert optimizely == optimizelyManager.getOptimizely();
          Intent intent = new Intent(FirstActivity.this, SubsequentActivity.class);
          startActivity(intent);
      }
    });


A solution here can be to add an onFailure call to the OptimizelyStartListener.

**Comment by javierarboleda** [comment]
> Can you try adding this to your gradle file dependancies and see if the issue still comes up in API 17?
compile group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version:'1.7.1'

Gave this a shot, but it didn't work (same `NoClassDefFoundError: javax/annotation/Nonnull` error)

**Comment by thomaszurkan-optimizely** [comment]
How about compile `group: 'com.google.code.findbugs', name: 'jsr305', version: '2.0.1'`?

**Comment by javierarboleda** [comment]
> I've been trying to reproduce and I've been unable to do so. Unfortunately, we only have API 17 on emulator. Are you experiencing the exception in the emulator as well?

I'm testing on our Clover devices, I've never had a reason to do any testing on emulators. However, we do provide some docs on how to set up a Clover device emulator (https://docs.clover.com/build/android-emulator-setup/). I'll see if it's reproducible there.

**Comment by javierarboleda** [comment]
> How about compile group: 'com.google.code.findbugs', name: 'jsr305', version: '2.0.1'?

That did the trick! I'll keep testing with this, make sure no side effects on other devices. Thanks so much!

**Comment by javierarboleda** [comment]
@thomaszurkan-optimizely 
Hey man, if you have a minute, can you explain a bit on the above solution? Is this more of a workaround than a fix?

Please excuse my ignorance, but from glancing at this, I'm not following much how this is helping avoid the NoClassDefFoundError issue.

Thanks for looking at this and any info/explanation you can share!!

**Comment by thomaszurkan-optimizely** [comment]
I would say it is a workaround instead of a fix.  Essentially, javax for android is only a subset of what is available for java.  So, there is a bunch of garbage we could have gone through to try and include a jar with all the javax packages.  However, Optimizely uses findbugs in the core java sdk and it includes javax.annotations.  So, we are piggybacking on that.  I hope that makes sense.

**Comment by thomaszurkan-optimizely** [comment]
@javierarboleda we have released 1.5.0-RC which includes the above fix so that there will be no crash on API 17 and you no longer need to include it at your end.  This issue will be closed soon.

**Comment by thomaszurkan-optimizely** [comment]
Fixed in our gradle build file.
