### ISSUE TITLE
1.5.0-RC Multiple Dex Files define class 

### ISSUE THREAD

**Issue by marcoRS** [optimizely/android-sdk#161]
I am seeing the following error in our project: 
```
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
Caused by: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:72)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Caused by: com.android.dex.DexException: Multiple dex files define Lcom/noveogroup/android/log/AbstractLogger;
```

Optimizely seems to be the only library with this dependency so I don't know why the clash  dex merging.

**Comment by thomaszurkan-optimizely** [comment]
If you look at the release 1.5 test-app, it shows how to remove the noveogroup as a compile exclude.  That should do it.  But, I'm not sure why you would get double define there.  It is only included once in Optimizely Android SDK.

**Comment by thomaszurkan-optimizely** [comment]
@marcoRS how are you building?

**Comment by thomaszurkan-optimizely** [comment]
By the way, I saw this error and it was fixed by clearing my .gradle cache.

**Comment by thomaszurkan-optimizely** [comment]
@marcoRS feel free to open this back up if you think I am closing it in error.  Thanks!

**Comment by marcoRS** [comment]
Cleaning the Gradle cache folder did not work for me. I excluded the library the way it is excluded in the test-app and that seemed to do the trick. Thanks!

**Comment by thomaszurkan-optimizely** [comment]
@marcoRS, thank you!  Also, can you upgrade to 1.5.1.  The proguard rules were a little to relaxed.

**Comment by thomaszurkan-optimizely** [comment]
Please use 1.5.1
