### ISSUE TITLE
SDK crashing app...

### ISSUE THREAD

**Issue by rrob9966** [optimizely/android-sdk#173]
Keep getting crash reports from our Crashlytics regarding error below. Please advise. Could not reproduce the issue in our test. Error seems to happen on Android O (8.0, 8.1).

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.optimizely.OptlyIoReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.optimizely.io.action.SCHEDULE cmp=com.thrivemarket.app/com.optimizely.OptlyIoService }: app is in background uid UidRecord{eef43ca u0a173 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=com.optimizely.io.action.SCHEDULE cmp=com.thrivemarket.app/com.optimizely.OptlyIoService }: app is in background uid UidRecord{eef43ca u0a173 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.optimizely.OptlyIoReceiver.onReceive(OptlyIoReceiver.java:22)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by thomaszurkan-optimizely** [comment]
@rrob9966 are you running Android SDK 1.5.1? That is the SDK with Android O and above support

**Comment by thomaszurkan-optimizely** [comment]
@rrob9966 this is the class android mobile sdk which is a different repo and no longer supported.  I'm closing this issue.
