### ISSUE TITLE
RemoteException 

### ISSUE THREAD

**Issue by jia-tse-zocdoc** [optimizely/android-sdk#269]
Hi, we're seeing a lot of crashes for Android 8 and above, stack trace looks like this.  This may be different than the SecurityException that was reported years ago.... 

```
JobIntentService$JobServiceEngineImpl line 315
android.support.v4.app.JobIntentService$JobServiceEngineImpl.dequeueWork
```

```
Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:481)
	at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:359)
	at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
	at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83)
	at android.os.Binder.execTransact(Binder.java:731)
```

```
Caused by java.lang.SecurityException: Caller no longer running, last stopped +1s424ms because: timed out while starting
       at android.os.Parcel.readException(Parcel.java:1943)
       at android.os.Parcel.readException(Parcel.java:1889)
       at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
       at android.app.job.JobParameters.dequeueWork(JobParameters.java:196)
       at android.support.v4.app.JobIntentService$JobServiceEngineImpl.dequeueWork(SourceFile:315)
       at android.support.v4.app.JobIntentService.dequeueWork(SourceFile:640)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(SourceFile:390)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(SourceFile:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by thomaszurkan-optimizely** [comment]
@jia-tse-zocdoc we have the deque wrapped in a try catch.  so, there should not be a crash if there was a problem in dequeue.  are you sure there is a crash?

**Comment by thomaszurkan-optimizely** [comment]
@jia-tse-zocdoc I have confirmed that this is not a crash.

**Comment by jia-tse-zocdoc** [comment]
I wonder why it shows up like this in crashlytics...

![image](https://user-images.githubusercontent.com/27829624/56666113-508cee00-6679-11e9-87f5-4a5942b822d6.png)

**Comment by jia-tse-zocdoc** [comment]
@thomaszurkan-optimizely  -- I think you're right. Looks like what I saw were old errors, and it stopped happening.

**Comment by paralytic123** [comment]
Hello, has this problem been solved? I am also experiencing this problem when using JobIntentService now, I don't know how to solve it

Remote stack trace: at com.android.server.job.JobServiceContext.assertCallerLocked(JobServiceContext.java:487)
at com.android.server.job.JobServiceContext.doDequeueWork(JobServiceContext.java:365)
at com.android.server.job.JobServiceContext$JobCallback.dequeueWork(JobServiceContext.java:160)
at android.app.job.IJobCallback$Stub.onTransact(IJobCallback.java:83) at android.os.Binder.execTransact(Binder.java:732)
