### ISSUE TITLE
Caused by java.lang.OutOfMemoryError Failed to allocate a 7408792 byte allocation with 1931064 free bytes and 1869KB until OOM, max allowed footprint 134217728, growth limit 134217728

### ISSUE THREAD

**Issue by paulwang007** [optimizely/android-sdk#333]
SDK Version: 3.5.1

<img width="452" alt="Screen Shot 2020-06-04 at 11 42 11" src="https://user-images.githubusercontent.com/5761415/83798106-924bde80-a658-11ea-9246-3f4a1d6c81e2.png">

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:353)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.OutOfMemoryError: Failed to allocate a 7408792 byte allocation with 1931064 free bytes and 1869KB until OOM, max allowed footprint 134217728, growth limit 134217728
       at java.util.Arrays.copyOf(Arrays.java:3164)
       at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
       at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
       at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
       at java.io.OutputStream.write(OutputStream.java:75)
       at sun.security.util.DerValue.encode(DerValue.java:425)
       at sun.security.util.DerValue.toByteArray(DerValue.java:861)
       at sun.security.x509.X509CRLImpl.parse(X509CRLImpl.java:1094)
       at sun.security.x509.X509CRLImpl.<init>(X509CRLImpl.java:146)
       at sun.security.provider.X509Factory.intern(X509Factory.java:206)
       at sun.security.x509.X509CRLImpl.toImpl(X509CRLImpl.java:1235)
       at sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:396)
       at sun.security.provider.certpath.DistributionPointFetcher.verifyCRL(DistributionPointFetcher.java:667)
       at sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:209)
       at sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:121)
       at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:552)
       at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
       at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
       at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
       at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
       at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
       at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
       at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
       at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:703)
       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:560)
       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605)
       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:197)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:399)
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:283)
       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:156)
       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:119)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:257)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:478)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:140)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
       at com.google.firebase.perf.network.zzd.connect(zzd.java:13)
       at com.google.firebase.perf.network.zze.connect(zze.java:5)
       at com.optimizely.ab.android.datafile_handler.DatafileClient$1.execute(DatafileClient.java:82)
       at com.optimizely.ab.android.datafile_handler.DatafileClient$1.execute(DatafileClient.java:66)
       at com.optimizely.ab.android.shared.Client.execute(Client.java:143)
       at com.optimizely.ab.android.datafile_handler.DatafileClient.request(DatafileClient.java:111)
       at com.optimizely.ab.android.datafile_handler.DatafileLoader$RequestDatafileFromClientTask.doInBackground(DatafileLoader.java:122)
       at com.optimizely.ab.android.datafile_handler.DatafileLoader$RequestDatafileFromClientTask.doInBackground(DatafileLoader.java:86)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by msohailhussain** [comment]
Hi Paul, 
Can I have some more details to repro this issue? e.g. What's the configuration for OptimizelyManager?

**Comment by mikeng13** [comment]
@paulwang007 thanks for submitting. Like my colleague asked, could you please provide some more context to this? 

Can you share the snippet of code you are using the initialize the SDK and where in the app this is happening? Also, it would help to know the SDK key you are using. If you don't mind, please file a Zendesk ticket with your support rep with the SDK key so we can look check out your datafile. Conversely, if you can just tell us what the size of your datafile is that might work too. but having your SDK key would help with a repro.

**Comment by thomaszurkan-optimizely** [comment]
@paulwang007 
https://github.com/google/conscrypt/issues/520
This seems to be a similar stack trace and issue. 

We did a few things to make sure datafile requests don’t pill up. We also updated build tools 29.0.3.

**Comment by paulwang007** [comment]
@mikeng13 @thomaszurkan-optimizely @msohailhussain We will create a ZenDesk ticket and provide more info.
