### ISSUE TITLE
android.os.DeadSystemException：Unable to unbind|create  service

### ISSUE THREAD

**Issue by senlsy** [optimizely/android-sdk#344]
First Crash：
Fatal Exception: java.lang.RuntimeException: Unable to unbind to service com.optimizely.ab.android.datafile_handler.DatafileService@4b3f953 with Intent { cmp=com.verifly.smb/com.optimizely.ab.android.datafile_handler.DatafileService }: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.ActivityThread.handleUnbindService(ActivityThread.java:4139)
       at android.app.ActivityThread.access$1700(ActivityThread.java:226)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Second Crash：
Fatal Exception: java.lang.RuntimeException: Unable to create service com.optimizely.ab.android.shared.ScheduledJobService: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4081)
       at android.app.ActivityThread.access$1500(ActivityThread.java:226)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by senlsy** [comment]
I want to use both synchronous and asynchronous initialization methods，this my init code：

public ABUtils init(Application application) {
        try {
            OptimizelyManager manager = OptimizelyManager.builder()
                    .withSDKKey(BuildConfig.ABTEST_KEY)
                    .withDatafileDownloadInterval(60L * 10L)
                    .build(application);

            mSyncOptyClient = manager.initialize(application, R.raw.datafile);
            Log.e("Optly", "mSyncOptyClient=%s, thread info:%s", mSyncOptyClient, Thread.currentThread().getName());

            OptimizelyManager.builder()
                    .withSDKKey(BuildConfig.ABTEST_KEY)
                    .withDatafileDownloadInterval(60L * 10L)
                    .build(application)
                    .initialize(application, null, (OptimizelyClient optimizely) -> {
                        Log.e("Optly", "mAsyncOptyClient initialized, thread info:%s", Thread.currentThread().getName());
                        mAsyncOptyClient = optimizely;
                    });


        } catch (Exception e) {
            Log.exception(e);
        }

        return this;
    }

**Comment by thomaszurkan-optimizely** [comment]
@senlsy Multiple instances in Android can cause problems. Especially if they are sharing an sdk key.  It is not supported at this time in the android sdk. What is happening here is that the datafile intent is finishing for one instance and releases the binding. Later the second also try’s to unbind but it is already unbound.

You may be able to get around the issue if you share the datafile handler and event processor.

**Comment by senlsy** [comment]
@thomaszurkan-optimizely  Thanks!!!
