### ISSUE TITLE
Datafile download fails on API 16

### ISSUE THREAD

**Issue by nathan-l** [optimizely/android-sdk#366]
Hi. 
When downloading a file with the default DataFileClient, `urlConnection.connect();` fails with an ssl error, here is the full stacktrace. 

```javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x68a5f008: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x671c3d74:0x00000000)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
	at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
	at com.android.okhttp.Connection.connect(Connection.java:107)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
	at com.optimizely.ab.android.datafile_handler.DatafileClient$1.execute(DatafileClient.java:84)
	at com.optimizely.ab.android.datafile_handler.DatafileClient$1.execute(DatafileClient.java:68)
	at com.optimizely.ab.android.shared.Client.execute(Client.java:143)
	at com.optimizely.ab.android.datafile_handler.DatafileClient.request(DatafileClient.java:113)
	at com.optimizely.ab.android.datafile_handler.DatafileLoader$1.run(DatafileLoader.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x68a5f008: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x671c3d74:0x00000000)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
```

I think this is happening because android <20 don't support TLS1.2+ by default.

**Comment by jaeopt** [comment]
@nathan-l Thanks for sharing. We'll take a look at it.

**Comment by thomaszurkan-optimizely** [comment]
@nathan-l , if you are using google play there is an easy solution using provider installer [here].(https://guides.codepath.com/android/Using-OkHttp#enabling-tls-v1-2-on-older-devices)

**Comment by nathan-l** [comment]
Thanks @jaeopt. @thomaszurkan-optimizely, unfortunately a signifant part of our clients are not running google play so we can' t rely on the gms provider to solve this.

We are using a custom SSLSocketFactory that we set in our OkHttp instance to support TLS1.2 on our API; but this solution isn't applicable to the SDK http client.

**Comment by jaeopt** [comment]
@nathan-l SDK 3.10.2 has been released with the TSL support for API-16+
