### ISSUE TITLE
Crash with java.lang.ExceptionInInitializerError caused by java.lang.IllegalStateException: FileLogger is not initialized. Forgot to call Log4O.init()?

### ISSUE THREAD

**Issue by ingridswiftconnect** [optimizely/android-sdk#449]
I have another library in my project that uses "com.noveogroup.android:android-logger:1.3.6".  Also I am using this version of the lib ->     implementation 'com.optimizely.ab:android-sdk:3.13.3'

**Comment by jaeopt** [comment]
@ingridswiftconnect We use android-logger in our test-app only. It's not used in our SDK.
Can you share stack trace?

**Comment by ingridswiftconnect** [comment]
E  FATAL EXCEPTION: main
                                                                                                    Process: com.swiftctrl.example, PID: 28050
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at com.optimizely.ab.internal.PropertyUtils.getInteger(PropertyUtils.java:213)
                                                                                                    	at com.optimizely.ab.event.BatchEventProcessor$Builder.<init>(BatchEventProcessor.java:241)
                                                                                                    	at com.optimizely.ab.event.BatchEventProcessor.builder(BatchEventProcessor.java:235)
                                                                                                    	at com.optimizely.ab.android.sdk.OptimizelyManager$Builder.build(OptimizelyManager.java:944)
                                                                                                    	at com.swiftctrl.android.App.onCreate(App.kt:42)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.IllegalStateException: FileLogger is not initialized. Forgot to call Log4O.init()?

**Comment by russell-loube-optimizely** [comment]
Hi @ingridswiftconnect , we have reviewed this as a team and added a research item to our backlog. We unfortunately don't have a timeline for when we'll pick this up at the moment, but we'll inform you here when we do. Thank you.

**Comment by russell-loube-optimizely** [comment]
Hi @ingridswiftconnect , we are currently looking at this issue in our active sprint. One of our engineers created a new Android application and imported the same libraries. We haven't been able to replicate the issue as of yet.

We'll contact you here in case we need any additional information to continue troubleshooting.

**Comment by ingridswiftconnect** [comment]
Hello,

The problem was because of another library , but it was fixed on their
side. We could close this ticket.

Thank you!

**Comment by Tamara-Barum** [comment]
Closing per the above comment.
