### ISSUE TITLE
ResourcesNotFoundException thrown during initialisaiton

### ISSUE THREAD

**Issue by barchynskyi** [optimizely/android-sdk#458]
SDK version: 3.10.1
Android version: multiple

Recently we have detected issue during the SDK init. Looks like Optimizely throws exception outside error handler and leads to broken and unrecoverable Optimizely state. We could not identify steps to reproduce the issue but it looks like it happens during synchronous initialisation.

Stacktrace:
`android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
                                                                                                    	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:269)
                                                                                                    	at android.content.res.ResourcesImpl.openRawResource(ResourcesImpl.java:425)
                                                                                                    	at android.content.res.Resources.openRawResource(Resources.java:1461)
                                                                                                    	at android.content.res.Resources.openRawResource(Resources.java:1405)
                                                                                                    	at com.optimizely.ab.android.sdk.OptimizelyManager.loadRawResource(OptimizelyManager.java:457)
                                                                                                    	at com.optimizely.ab.android.sdk.OptimizelyManager.safeLoadResource(OptimizelyManager.java:387)
                                                                                                    	at com.optimizely.ab.android.sdk.OptimizelyManager.getDatafile(OptimizelyManager.java:340)
                                                                                                    	at com.optimizely.ab.android.sdk.OptimizelyManager.initialize(OptimizelyManager.java:264)`

**Comment by Tamara-Barum** [comment]
Opening an internal ticket to review:
FSSDK-9406

**Comment by mnoman09** [comment]
@barchynskyi could you please share the code which you are using for OptimizelySDK initialization?

**Comment by Tamara-Barum** [comment]
Issue has been confirmed resolved..
